# Generated by Django 4.2.8 on 2024-06-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camionneur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('numero_de_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('numero_de_permis', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('entreprise_employeur', models.CharField(max_length=100)),
                ('type_de_camion_conduit', models.CharField(max_length=100)),
                ('disponibilite', models.BooleanField(default=True)),
                ('statut_d_emploi', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_de_la_livraison', models.DateField()),
                ('adresse_de_depart', models.CharField(max_length=255)),
                ('adresse_de_destination', models.CharField(max_length=255)),
                ('type_de_marchandise', models.CharField(max_length=100)),
                ('poids_de_la_marchandise', models.FloatField()),
                ('statut_de_la_livraison', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_cours', max_length=10)),
                ('camionneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='comionneur.camionneur')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('plaque_d_immatriculation', models.CharField(max_length=20)),
                ('capacite_de_charge', models.FloatField()),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('en_reparation', 'En réparation')], default='en_service', max_length=15)),
                ('camionneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comionneur.camionneur')),
            ],
        ),
    ]
