# Generated by Django 4.2.8 on 2024-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comionneur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionneur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
