# Generated by Django 4.2.8 on 2024-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comionneur', '0002_camionneur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionneur',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
