# Generated by Django 4.2.8 on 2024-06-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comionneur', '0003_camionneur_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
