# Generated by Django 4.2.8 on 2024-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comionneur', '0006_alter_camionneur_options_alter_camionneur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionneur',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
    ]
