# Generated by Django 4.2.8 on 2024-06-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comionneur', '0004_delete_livraison'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_de_la_livraison', models.DateField()),
                ('adresse_de_depart', models.CharField(max_length=255)),
                ('adresse_de_destination', models.CharField(max_length=255)),
                ('type_de_marchandise', models.CharField(max_length=100)),
                ('poids_de_la_marchandise', models.FloatField()),
                ('statut_de_la_livraison', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_cours', max_length=10)),
                ('camionneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='comionneur.camionneur')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='gestion.order')),
            ],
        ),
    ]
