# Generated by Django 4.2.8 on 2024-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_groups_alter_client_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile_picture',
            new_name='photo',
        ),
    ]
